apiVersion: v1
kind: ConfigMap
metadata:
  name: config-coredns
  labels:
    type: config
data:
  Corefile: |-
    .:53 {
        cache 30
        errors stderr
        etcd slateci. {
          path /skydns
          endpoint http://etcd.default:2379
        }
        health
        loadbalance round_robin
        prometheus localhost:9153
        proxy . /etc/resolv.conf
    }
