apiVersion: v1
kind: Service
metadata:
  labels:
    app: coredns
  name: coredns
spec:
  ports:
  - name: dns
    nodePort: 32222
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    nodePort: 32222
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app: coredns
  type: NodePort
