apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-entrypoint
data:
  entrypoint.sh: |
    #!/bin/sh
    echo "$HOSTNAME" > /usr/share/nginx/html/index.html

    exec nginx -g "daemon off;"

---

apiVersion: v1
kind: Service
metadata:
  name: spread
  labels:
    name: spread
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: spread
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spread
  labels:
    app: spread
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spread
  template:
    metadata:
      labels:
        app: spread
    spec:
      containers:
      - image: nginx:stable-alpine
        name: spread
        command: [ "./scripts/entrypoint.sh" ]
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: entrypoint
          mountPath: /scripts
      volumes:
      - name: entrypoint
        configMap:
          name: nginx-entrypoint
          defaultMode: 0755
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spread
  namespace: default
spec:
  rules:
  - host: spread.default.minifed.svc.myfed
    http:
      paths:
      - backend:
          serviceName: spread
          servicePort: 80
        path: /
