apiVersion: v1
kind: Service
metadata:
  name: selector
  labels:
    name: selector
  annotations:
    federation.kubernetes.io/service-ingresses: |
      {
        "items": [{
          "cluster": "alpha",
          "items": [{
            "ip": "__ALPHA__",
            "hostname": "__ALPHA__"
          }]
        }]
      }
    federation.alpha.kubernetes.io/cluster-selector: |
      [{
        "key": "gpu",
        "operator": "In",
        "values": ["true"]
      }]
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: selector
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: selector
  labels:
    app: selector
  annotations:
    federation.alpha.kubernetes.io/cluster-selector: |
      [{
        "key": "gpu",
        "operator": "In",
        "values": ["true"]
      }]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selector
  template:
    metadata:
      labels:
        app: selector
    spec:
      containers:
      - image: nginx
        name: selector
        command: [ "./scripts/entrypoint.sh" ]
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: entrypoint
          mountPath: /scripts
      volumes:
      - name: entrypoint
        configMap:
          name: nginx-entrypoint
          defaultMode: 0755
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: selector
  namespace: default
  annotations:
    federation.alpha.kubernetes.io/cluster-selector: |
      [{
        "key": "gpu",
        "operator": "In",
        "values": ["true"]
      }]
spec:
  rules:
  - host: selector.default.fed.svc.slateci
    http:
      paths:
      - backend:
          serviceName: selector
          servicePort: 80
        path: /
